name: pdf_converse
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_dotenv:
  syncfusion_flutter_pdf:
  path_provider:
  langchain: ^0.5.0+1
  pinecone: ^0.7.2
  langchain_openai: ^0.5.0+1
  langchain_pinecone:




  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  custom_lint:
  riverpod_generator:
  riverpod_lint:



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/pdf/
    - .env

